name: Build

on:
  workflow_call:
    inputs:
      actor:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: deployment

    steps:
      - uses: actions/checkout@v4.1.2
      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: corretto
      - name: Build with Gradle
        run: ./gradlew assemble
        env:
          GITHUB_AUTHOR: ${{ inputs.actor }}
          GITHUB_TOKEN: ${{ secrets.token }}
