name: "Continuous Deployment"
on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      env-name:
        required: true
        type: string

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Create Short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 8

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
           ghcr.io/ingsis-grupo1-2024/${{inputs.image-name}}-${{inputs.env-name}}:${{ steps.short-sha.outputs.sha }}
           ghcr.io/ingsis-grupo1-2024/${{inputs.image-name}}-${{inputs.env-name}}:latest
           
          build-args: |
            ACTOR=${{ github.repository_owner }}
            TOKEN=${{ secrets.GITHUB_TOKEN }}
  deploy:
    uses: IngSis-Grupo1-2024/snippet-infra/.github/workflows/deploy-${{inputs.env-name}}.yml@main
    needs: push_to_registry
    secrets: inherit
    with:
      container-name: ${{inputs.image-name}}
