name: "Continuous Deployment"

on:
  workflow_call:
    inputs:
      container-name:
        required: true
        type: string
    secrets:
      VM_KEY:
        required: true
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VM_KEY }}

      - name: Connect to VM and rebuild container
        run: |
          ssh -o StrictHostKeyChecking=no ingsis-group1@51.8.88.134 << 'EOF'
            cd snippet-infra
            sudo docker-compose -f docker-compose-dev.yml stop ${{ inputs.container-name }}
            sudo docker-compose -f docker-compose-dev.yml up --build -d ${{ inputs.container-name }}
          EOF
        shell: bash
