name: "Production Continuous Deployment"

on:
  workflow_call:
    inputs:
      container-name:
        required: true
        type: string
    secrets:
      PROD_VM_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PROD_VM_KEY }}

      - name: Connect to VM and rebuild container
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@20.42.96.135 << 'EOF'
            cd snippet-infra
            sudo docker-compose -f docker-compose-main.yml stop ${{ inputs.container-name }}
            sudo docker-compose -f docker-compose-main.yml up --build -d ${{ inputs.container-name }}
          EOF
        shell: bash
